authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
     path('', views.home, name="home"),
     path('Register', views.Register, name="Register"),
     path('Login', views.Login, name="Login"),
     path('Logout', views.Logout, name="Logout"),
    
]

comments/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.add_comment, name='comments'),
    path('comments', views.show_comments, name='show_comments'),
    
    
    
]

gradproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('authentication.urls')),
    path('', include('comments.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

comments/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

authentication/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def home(request):
    return render(request,"authentication/index.html")

def Register(request):
    
    if request.method == "POST":
       # username = request.POST.get('username')
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exist please try some other username")
            return redirect('home')

        if User.objects.filter(email=email):
            messages.error(request, "Email already registered!")
            return redirect('home')
        
        if len(username)>15:
            messages.error(request, "Username must be under 15 characters")

        if pass1 != pass2:
            messages.error(request, "Passwords didn't match!")
            



        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname

        myuser.save()

        messages.success(request, "Your Account has been successfully created")

        return redirect('Login')

    return render(request, "authentication/Register.html")

def Login(request):

    if request.method == "POST":
        username = request.POST['username']
        pass1 = request. POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            login(request, user)
            fname = user.first_name
            return render(request, "authentication/index.html", {'fname': fname})

        else:
            messages.error(request, "Bad Credentials")
            return redirect('home')    


     

    return render(request, "authentication/Login.html")

def Logout(request):
    logout(request)
    messages.success(request, "logged Out Successfully!")
    return redirect('home')

comments/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import CommentForm
from .models import Comment




def add_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('show_comments')  # Redirect to the appropriate view after comment submission
    else:
        form = CommentForm()
    return render(request, 'comments/comment_form.html', {'form': form})

from .models import Comment

def show_comments(request):
    comments = Comment.objects.order_by('-created_at')
    return render(request, 'comments/comments.html', {'comments': comments})

templates/authentication/Login.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h3>Registration</h3>

        <form action="/Login" method="Post">
            {% csrf_token %}
         
            <label for="">Username</label>
            <input type="text" id="username" name="username" placeholder="Enter Your Username" Required>
            <br>

            <label for="">password</label>
            <input type="password" id="password" name="pass1" placeholder="Enter Your Password" Required>
            <br>

            
            <button type="submit">Log In</button>
        </form>
        
        <script src="" async defer></script>
    </body>
</html>

templates/authentication/Register.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h3>Registration</h3>

        <form action="/Register" method="Post">
            {% csrf_token %}
         
            <label for="">Username</label>
            <input type="text" id="username" name="username" placeholder="Create a username (only letters and numbers)" Required>
            <br>

            <label for="">First Name</label>
            <input type="text" id="fname" name="fname" placeholder="Enter Your First Name" Required>
            <br>

            <label for="">Last Name</label>
            <input type="text" id="lname" name="lname" placeholder="Enter Your Last Name" Required>
            <br>

            <label for="">Email Address</label>
            <input type="email" id="email" name="email" placeholder="Enter Your Email Address" Required>
            <br>

            <label for="">Password</label>
            <input type="password" id="pass1" name="pass1" placeholder="Create a Password" Required>
            <br>

            <label for="">Confirm your password</label>
            <input type="password" id="pass2" name="pass2" placeholder="Confirm Your Password" Required>
            <br>
            <button type="submit">Register</button>
        </form>
        
        <script src="" async defer></script>
    </body>
</html>

templates/authentication/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Authentication</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
        {%for message in messages%}
        <div class = "alert alert-{{message.tags}} alert-dismissible fade show" role= "alert">
        <strong>Message: </strong> {{ message}}
        <button type="button" class= "close" data-dismiss= "alert" aria-label="close">
        </button>
        <span aria-hidden= "true">&times;</span>
        
        </div>
        {% endfor %}



        <h3>Welcome to Major Selector</h3>

        {% if user.is_authenticated%}
        <h3>Hello {{ fname }}</h3>
        <h4>You're successfully logged in.</h4>
        <button type="submit"><a href="/Logout">Logout</a></button>


        {% else %}
        <button type="submit"><a href="/Register">Register</a></button>
        <button type="submit"><a href="/Login">Login</a></button>
        {% endif %}


        
        
        <script src="" async defer></script>
    </body>
</html>

templates/comments/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Experience</title>
</head>
<body>
    <h1>Add Your Experience</h1>
    <form action="{% url 'comments' %}" method="post">
        {% csrf_token %}
        <label for="id_name"> Name:</label><br>
        {{ form.name }}
        <br>
        <label for="id_email"> Email (optional):</label><br>
        {{ form.email }}
        <br>
        <label for="id_body">Your Comment:</label><br>
        {{ form.body }}
        <br>
       

        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/comments/comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explore Experiences</title>
</head>
<body>
    <h1>Experiences</h1>
    {% for comment in comments %}
        <div class="comment">
            <p>{{ comment.name }}:</p>
            <p>{{ comment.body }}</p>
            <p>Posted on: {{ comment.created_at }}</p>
            <br>
        </div>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}

    <hr>

    <!-- Comment Form -->
    <h2></h2>
    <form action="{% url 'comments' %}" method="post">
        {% csrf_token %}
        
    </form>
</body>
</html>